### ISSUE TITLE
Storage issue with multiple AuthenticationAdapter

### ISSUE THREAD

**Issue by lampi87** [LM-Commons/LmcUser#10]
Hello everyone,

I ran into an issue using multiple auth adapters and their `$this->isSatisfied()` function.
In File src/LmcUser/Authentication/Adapter/AbstractAdapter.php on line 24 the Storage is initialized using the current class name:
`$this->setStorage(new Storage\Session(get_class($this)));`

If I use multiple classes, e.g Db.php and a custom Ldap.php the class_name differs. If authentication is satisfied using Ldap (first adapter), Db should be skipped. But as the class_name differs a new storage is created an authentication fails.

My temporary workaround was to change this line to `$this->setStorage(new Storage\Session('LmcUser'));` and all AuthenticationAdapters are using the same storage.

This works for me, but is this the correct way ?

Best regards,
Alexander

**Comment by alexz707** [comment]
Hello Alexander,

I would say you are right. 
It's not a good idea that the Storage Session Name depends on the class.
This should be a unique name for the LmcUser Module.

I will look into it and make a PR.

Regards Alex

**Comment by lampi87** [comment]
Thank you for your reply and confirmation of my workaround.
I can create a PR too, but unfortunately I already made an open pull request for CSRF which is not yet resolved. So I'm not able to create a second PR
