### ISSUE TITLE
Laminas version 3 support.

### ISSUE THREAD

**Issue by jarrettj** [LM-Commons/LmcUser#26]
Hey,

Good day.

Any plans to have this run on Laminas version 3? Thanks.

Regards.
Jarrett

**Comment by rarog** [comment]
What do you mean? laminas-form v3? If this is what you meant, I at least supplied the pull request #25 to support this.

**Comment by jarrettj** [comment]
Hey, sorry, let me close this. I had other composer dependencies and eventually got it all setup fine. Thanks @rarog.
