### ISSUE TITLE
UnitTest are not executed

### ISSUE THREAD

**Issue by alexz707** [LM-Commons/LmcUser#3]
Hi!

i just had a look at your repo and it seems that the unit tests are not executed anymore:

`$ ./vendor/bin/phpunit --bootstrap=tests/bootstrap.php --configuration tests/phpunit.xml

PHPUnit 9.2.6 by Sebastian Bergmann and contributors.

Runtime:       PHP 7.4.10 with Xdebug 2.9.6

Configuration: tests/phpunit.xml

Error:         Incorrect whitelist config, no code coverage will be generated.

No tests executed!`

Regards Alex

**Comment by alexz707** [comment]
I would suggest to use the travis config from the laminas team.
I have already used it in the LmcUserDoctrineOrm project. There I also the coveralls badges as well as the Laminas Coding Standard for phpcs

Would would you @matwright  and @visto9259 think about it?

Btw. the unit test's will have a deprecated warning with 9.4

**Comment by visto9259** [comment]
fixed a long time ago
