### ISSUE TITLE
Usage of Psr Container and minor directory structure change request. 

### ISSUE THREAD

**Issue by ALTAMASH80** [LM-Commons/LmcUser#32]
Hi,

  I wanted to ask what you people think about changing the Interopt Container with the Psr container and the change of directory structure from src/LmcUser/* to src/*. Thanks!

**Comment by visto9259** [comment]
I did a quick check and LmcUser is not depending on `interop-container`.  It relies on laminas-servicemanager which depends on`Psr/Container`.  Or I misunderstood your question?

But, yes, the directory structure is still PSR-0 (src/LmcUser).  It's not small change.  Nothing complicated but still needs work and validation to ensure not breaking changes.
I would do it on the next major release.

**Comment by ALTAMASH80** [comment]
Yes, totally agree with you on the fact that LmcUser is not dependent on interop-container I was suggesting that we should replace it with Psr/Container [here](https://github.com/LM-Commons/LmcUser/blob/master/src/LmcUser/Factory/Service/UserFactory.php#L5). Also in other factory instances. Thanks!

**Comment by visto9259** [comment]
I see your point.  There is class aliasing in laminas-servicemanager to alias Interop/Container with Psr/Container.
I guess it should be done at one point and that's a smaller change than changing from PSR-0 to PSR-4.  This should not have any breaking changes and could be a minor update.

**Comment by ALTAMASH80** [comment]
So, you approve of this change, right? Assign it to me I'll do it. Thanks!

**Comment by visto9259** [comment]
Yes on the change from Interop to Psr.
Let's create a separate issue for the PSR-0 to PSR-4 change.

**Comment by ALTAMASH80** [comment]
#34 
The change which we discussed is in the pull request. Thanks!
