### ISSUE TITLE
Fix suggested #49 

### ISSUE THREAD

**Issue by vrkansagara** [LM-Commons/LmcUser#51]
~~~php
      if (isset($data['user_id'])) {
        $data = $this->mapField('user_id', 'id', $data);
      }
~~~

https://github.com/LM-Commons/LmcUser/blob/341a0bd09542474c88c798e121f7ed74a74559cd/src/Mapper/UserHydrator.php#L64

#49

**Comment by visto9259** [comment]
As a I mentioned in the code review, the change should be made in the mapField() function as this is where the warning is raised. 
And making the change in the mapField() function will cover all cases where a fromKey is not found in the array.
