### ISSUE TITLE
AdapterChain does not reset the chained adapters

### ISSUE THREAD

**Issue by visto9259** [LM-Commons/LmcUser#74]
The `resetAdapters` method of the `AdapterChain` authentication adapter does not reset the chained adapters.

The method assumes that the chained adapters are attached to the shared event manager but this is not the case.  Chained adapters are attached to the event manager.

The code:
```php
$sharedManager = $this->getEventManager()->getSharedManager();

        if ($sharedManager) {
            $listeners = $sharedManager->getListeners(['authenticate'], 'authenticate');
            foreach ($listeners as $listener) {
                if (is_array($listener) && $listener[0] instanceof ChainableAdapter) {
                    $listener[0]->getStorage()->clear();
                }
            }
        }
````

There could be cases where the session container where the chained adapters are storing data may not have been clear when starting the login sequence.

Suggested solution is to add a new event `'reset'` and trigger the event (similar to `logout`).  Chained adapters would need to implement `reset` event listeners.

By the way, chained adapters should implement the `ListenerAggregateInterface` such that there is one call to the `attach()`method and let the adapter set its listeners as needed.

Same as https://github.com/ZF-Commons/ZfcUser/issues/689

**Comment by visto9259** [comment]
Thanks @lon9man,

No one, I think, is monitoring ZfcUser. I am not monitoring it. But at the same time, we should go through the list of open issues/PR and import any relevant items into this repository.

The ZF-Commons team should mark the repos as archived.

**Comment by lon9man** [comment]
When I made issue i migrated to Zend 3, so Laminas was unknown for me, especially this package. 
Strictly today I checked this code in sources and decided to visit github and check newer versions with hope that this place was fixed) and have seen your post with familiar things)

**Comment by visto9259** [comment]
Are you using LmcUser now?

Typically, when I consider using a repo, I always looked for signs of activity. If the last commit was a couple of years ago, it's a sign that noone is maintaining it.

**Comment by lon9man** [comment]
@visto9259, 
yes, i am using it now. 
after migration to laminas also migrated ZfcUser to LmcUser.

> I always looked for signs of activity

i also do this. 
but for documentation purpose created issue too. 
if it was not created - then i am unable to quote it here)
